# Generated by Django 3.2.5 on 2021-07-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='local',
            new_name='location',
        ),
    ]
