# Generated by Django 3.2.5 on 2021-07-21 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_auto_20210721_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', through='profiles.FollowerRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
